services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: edu_backend
    networks:
      - edu-chatbot-network
    env_file: .env
    volumes:
      - ./data:/app/data          # mount data để ingest script đọc được
    depends_on:
      - qdrant
      - redis
    restart: unless-stopped

  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    networks:
      - edu-chatbot-network
    ports:
      - "6333:6333"
    volumes:
      - qdrant_data:/qdrant/storage
    restart: always

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - edu-chatbot-network
    ports:
      - "6379:6379"
    command: redis-server --maxmemory ${REDIS_MAX_MEMORY:-256mb} --maxmemory-policy allkeys-lru --requirepass ${REDIS_PASSWORD:-password}
    volumes:
      - redis_data:/data
    restart: always

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: edu_frontend
    networks:
      - edu-chatbot-network
    ports:
      - "3000:3000"
    env_file: .env
    environment:
      - BACKEND_URL=http://backend:8000
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  qdrant_data:
    name: qdrant_data
  redis_data:
    name: redis_data

networks:
  edu-chatbot-network:
    name: edu-chatbot-network
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.20.0/24
          gateway: 172.30.20.1
